# Generated by Django 3.2.13 on 2022-11-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='like_count',
        ),
    ]
