# Generated by Django 3.2.13 on 2022-11-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
