# Generated by Django 3.2.13 on 2022-11-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_remove_review_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='review',
        ),
    ]
