# Generated by Django 3.2.13 on 2022-11-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_review_like_usersreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.CharField(choices=[('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
