# Generated by Django 3.2.13 on 2022-11-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_remove_restaurant_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
