# Generated by Django 3.2.13 on 2022-11-02 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bars', '0003_remove_restaurant_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='like_users',
            field=models.ManyToManyField(related_name='like_restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
