# Generated by Django 3.2.13 on 2022-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_nickname_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_string',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
