# Generated by Django 3.2.13 on 2022-11-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_image_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_string',
            field=models.TextField(null=True),
        ),
    ]
